env:
  global:
    - LC_CTYPE=en_US.UTF-8
matrix:
  include:
    - os: osx
      language: swift
      osx_image: xcode10.1
      before_install:
        - rvm install ruby-2.4.2
      install:
        - bundle install --without=documentation
      script:
        - set -o pipefail
        - xcodebuild -project SwiftFormat.xcodeproj -scheme "SwiftFormat (Framework)" -sdk macosx clean build test | bundle exec xcpretty
      after_success: bundle exec slather
    - os: linux
      dist: xenial
      sudo: required
      services: docker
      env: DOCKER_IMAGE=swift:5.0.3-xenial SWIFT_SNAPSHOT=5.0.3 SWIFT_VERSION=5.0.3 SWIFT_TEST_ARGS="--parallel"
      install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script: swift test
